# Sikit-Learn 라이브러리
- 머신러닝을 다루는 다양한 라이브러리가 있다.
- Tensorflow, Keras, Pytorch, Sikit-Learn

In [4]:
%pip install scikit-learn==1.0.2

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 26.5/26.5 MB 29.7 MB/s eta 0:00:00
  Attempting uninstall: scikit-learn
    Found existing installation: scikit-learn 1.2.2
    Uninstalling scikit-learn-1.2.2:
      Successfully uninstalled scikit-learn-1.2.2
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
bigframes 1.8.0 requires scikit-learn>=1.2.2, but you have scikit-learn 1.0.2 which is incompatible.


In [5]:
import sklearn
print(sklearn.__version__)

1.0.2


In [8]:
# Classification - 분류 알고리즘을 사용해서 꽃의 종류를 구분을 해보도록 하겠습니다.
from sklearn.datasets import load_iris
import pandas as pd

In [16]:
iris = load_iris()

iris.data # feature data
iris.target # label data

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [21]:
# train_test_split() -> 학습용 데이터셋과 테스트용 데이터 셋으로 분리하는 역할
from sklearn.model_selection import train_test_split

# X_train : 학습용 피처 데이터, X_test : 테스트용 피처 데이터
# Y_train : 학습용 피처 데이터,

X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size = 0.2, random_state = 123)

In [24]:
y_test
len(y_train)

120

In [27]:
# 2. 학습을 위한 알고리즘을 불러옵니다.
from sklearn.tree import DecisionTreeClassifier # 분류 알고리즘 (supervised learning)

dt_clf = DecisionTreeClassifier(random_state = 123)
dt_clf


DecisionTreeClassifier(random_state=123)

In [29]:
dt_clf.fit(X_train, y_train)

DecisionTreeClassifier(random_state=123)

In [32]:
predict = dt_clf.predict(X_test)
predict

array([1, 2, 2, 1, 0, 1, 1, 0, 0, 1, 2, 0, 1, 2, 2, 2, 0, 0, 1, 0, 0, 2,
       0, 2, 0, 0, 0, 2, 2, 0])

In [38]:
from sklearn.metrics import accuracy_score
accuracy_score(y_test, predict)

0.9666666666666667

In [42]:
df = pd.DataFrame(data = X_test, columns = iris.feature_names)

df['answer'] = y_test
df['predict'] = predict

df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                 6.3               2.5                4.9               1.5   
1                 6.8               3.0                5.5               2.1   
2                 6.4               2.8                5.6               2.2   
3                 5.6               3.0                4.1               1.3   
4                 4.9               3.6                1.4               0.1   
5                 6.0               3.0                4.8               1.8   
6                 6.3               2.3                4.4               1.3   
7                 4.4               3.2                1.3               0.2   
8                 4.4               2.9                1.4               0.2   
9                 5.5               2.6                4.4               1.2   
10                6.9               3.1                5.1               2.3   
11                5.5               4.2                1.4               0.2   
12                5.2               2.7                3.9               1.4   
13                6.5               3.0                5.5               1.8   
14                7.7               3.0                6.1               2.3   
15                6.5               3.0                5.8               2.2   
16                5.5               3.5                1.3               0.2   
17                4.3               3.0                1.1               0.1   
18                6.1               2.9                4.7               1.4   
19                4.8               3.0                1.4               0.3   
20                5.2               3.4                1.4               0.2   
21                6.3               2.8                5.1               1.5   
22                4.8               3.4                1.9               0.2   
23                6.1               3.0                4.9               1.8   
24                5.1               3.8                1.6               0.2   
25                5.4               3.4                1.7               0.2   
26                5.4               3.4                1.5               0.4   
27                5.6               2.8                4.9               2.0   
28                7.7               3.8                6.7               2.2   
29                5.0               3.6                1.4               0.2   

    answer  predict  
0        1        1  
1        2        2  
2        2        2  
3        1        1  
4        0        0  
5        2        1  
6        1        1  
7        0        0  
8        0        0  
9        1        1  
10       2        2  
11       0        0  
12       1        1  
13       2        2  
14       2        2  
15       2        2  
16       0        0  
17       0        0  
18       1        1  
19       0        0  
20       0        0  
21       2        2  
22       0        0  
23       2        2  
24       0        0  
25       0        0  
26       0        0  
27       2        2  
28       2        2  
29       0        0

In [46]:
iris = load_iris()
dt_clf = DecisionTreeClassifier()
dt_clf.fit(iris.data, iris.target)
pred = dt_clf.predict(iris.data)
accuracy_score(iris.target, pred)

1.0

In [ ]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()
scaler.fit(X_train)

X_train_scaled = scaler.transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 교차 검증
1. K Fold 검증
2. Stratified 검증
3. cross_val_score()
  - 검증을 쉽게 할 수 있도록 도와주는 함수

In [50]:
from sklearn.preprocessing import LabelEncoder

items = ['강남구', '송파구', '노원구', '마포구', '마포구',  '용산구', '용산구' ]

encoder = LabelEncoder()
encoder.fit(items)
labels = encoder.transform(items)
print('인코딩 변환값 : ', labels)

인코딩 변환값 :  [0 3 1 2 2 4 4]


In [53]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

items = ['강남구', '송파구', '노원구', '마포구', '마포구',  '용산구', '용산구' ]

items = np.array(items).reshape(-1, 1)
oh_encoder = OneHotEncoder()
oh_encoder.fit(items)
oh_labels = oh_encoder.transform(items)

print('원-핫 인코딩 데이터')
print(oh_labels.toarray())
print('원-핫 인코딩 데이터 차원')
print(oh_labels.shape)

원-핫 인코딩 데이터
[[1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1.]]
원-핫 인코딩 데이터 차원
(7, 5)


In [55]:
import pandas as pd

df = pd.DataFrame({'item' : ['강남구', '송파구', '노원구', '마포구', '마포구',  '용산구', '용산구' ]})

pd.get_dummies(df)

item_강남구  item_노원구  item_마포구  item_송파구  item_용산구
0      True     False     False     False     False
1     False     False     False      True     False
2     False      True     False     False     False
3     False     False      True     False     False
4     False     False      True     False     False
5     False     False     False     False      True
6     False     False     False     False      True

In [56]:
import pandas as pd

data = {'Fruit' : ['Apple', 'Banana', 'Cherry', 'Apple', 'Cherry'],
        'Color' : ['Red', 'Yellow', 'Red', 'Green', 'Red']}
df = pd.DataFrame(data)
df

Fruit   Color
0   Apple     Red
1  Banana  Yellow
2  Cherry     Red
3   Apple   Green
4  Cherry     Red

In [57]:
pd.get_dummies(df)

Fruit_Apple  Fruit_Banana  Fruit_Cherry  Color_Green  Color_Red  \
0         True         False         False        False       True   
1        False          True         False        False      False   
2        False         False          True        False       True   
3         True         False         False         True      False   
4        False         False          True        False       True   

   Color_Yellow  
0         False  
1          True  
2         False  
3         False  
4         False